# ====================================== AIRFLOW ENVIRONMENT VARIABLES =======================================
x-environment: &airflow_environment
  - AIRFLOW__CORE__EXECUTOR=LocalExecutor
  - AIRFLOW__CORE__LOAD_DEFAULT_CONNECTIONS=False
  - AIRFLOW__CORE__LOAD_EXAMPLES=False
  - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql://${AIRFLOWDB_USER}:${AIRFLOWDB_PASSWORD}@airflow_db:5432/${AIRFLOWDB_NAME}
  - AIRFLOW__CORE__STORE_DAG_CODE=True
  - AIRFLOW__CORE__STORE_SERIALIZED_DAGS=True
  - AIRFLOW__WEBSERVER__EXPOSE_CONFIG=True
  - AIRFLOW__CORE__ENABLE_XCOM_PICKLING=True

x-airflow-image: &airflow_image apache/airflow:2.9.0-python3.10
# ====================================== /AIRFLOW ENVIRONMENT VARIABLES ======================================

services:
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com  # Set your desired email
      PGADMIN_DEFAULT_PASSWORD: admin  # Set your desired password
    ports:
      - "5050:80"  # Map port 5050 on the host to port 80 in the container
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  taxi_db:
    image: postgres:13
    environment:
      - POSTGRES_USER=${TAXIDB_USER}
      - POSTGRES_PASSWORD=${TAXIDB_PASSWORD}
      - POSTGRES_DB=${TAXIDB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - taxiDB:/var/lib/postgresql/data

  airflow_db:
    image: postgres:13
    environment:
      - POSTGRES_USER=${AIRFLOWDB_USER}
      - POSTGRES_PASSWORD=${AIRFLOWDB_PASSWORD}
      - POSTGRES_DB=${AIRFLOWDB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - airflowDB:/var/lib/postgresql/data

  init:
    build:
      context: images/airflow-docker
      args:
        AIRFLOW_BASE_IMAGE: *airflow_image
    image: helloAirflow/airflow-docker
    container_name: helloAirflow_init
    restart: always
    depends_on:
      - taxi_db
      - airflow_db
    environment: *airflow_environment
    entrypoint: /bin/bash
    command: -c 'airflow db init && airflow users create --username admin --password admin --firstname Anonymous --lastname Admin --role Admin --email admin@example.org'

  webserver:
    build:
      context: images/airflow-docker
      args:
        AIRFLOW_BASE_IMAGE: *airflow_image
    image: helloAirflow/airflow-docker
    container_name: helloAirflow_webserver 
    restart: always
    depends_on:
      - taxi_db
      - airflow_db
    ports:
      - "8080:8080"
    volumes:
      - logs:/opt/airflow/logs
    environment: *airflow_environment
    command: webserver

  scheduler:
    build:
      context: images/airflow-docker
      args:
        AIRFLOW_BASE_IMAGE: *airflow_image
    image: helloAirflow/airflow-docker
    container_name: helloAirflow_scheduler 
    restart: always
    depends_on:
      - taxi_db
      - airflow_db
    volumes:
      - logs:/opt/airflow/logs
      - ./dags:/opt/airflow/dags
      - ./data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment: *airflow_environment
    command: scheduler

volumes:
  taxiDB:
  airflowDB:
  logs:
